export const profileFormData = {
  btnText: 'Next',
  inputs: [
    {
      type: 'formBreak',
      counter: '00',
      text: "Create a New Profile"
    },
    {
      name: 'name',
      label: 'Create a display name',
      icon: 'perm_identity',
      type: 'text',
      value: '',
    },
    {
      name: 'gender',
      label: "I'm a",
      type: 'radio',
      value: 'Male',
      options: ['Male', 'Female'],
    },
    {
      name: 'lookingfor',
      label: "I'm looking for a",
      type: 'radio',
      value: 'Female',
      options: ['Male', 'Female'],
    },
    {
      type: 'formBreak',
      counter: '01',
      text: "Create a New Profile"
    },
    {
      name: 'work',
      label: '',
      icon: 'work',
      type: 'select',
      value: '',
      options: [
        'Enter Your Work Details',
        'Company Job',
        'Govt. Job',
        'Business',
      ]
    },
    {
      name: 'workSector',
      label: '',
      icon: 'work',
      type: 'select',
      value: '',
      options: [
        'Enter Your Work Sector',
        'Education',
        'IT/Software',
        'Food',
        'Goods',
        'Transport',
        'Insurance',
        'Banking',
        'Public Service',
      ]
    },
    {
      type: 'formBreak',
      counter: '02',
      text: "Location Details"
    },
    {
      name: 'state',
      label: '',
      icon: 'location_searching',
      type: 'select',
      value: '',
      options: [
        'Which state are you located?',
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jammu and Kashmir',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttarakhand',
        'Uttar Pradesh',
        'West Bengal',
        'Andaman and Nicobar Islands',
        'Chandigarh',
        'Dadra and Nagar Haveli',
        'Daman and Diu',
        'Delhi',
        'Lakshadweep',
        'Puducherry',
      ],
    },
    {
      name: 'city',
      label: 'Which city are you located?',
      icon: 'location_on',
      type: 'text',
      value: '',
    },
    {
      type: 'formBreak',
      counter: '03',
      text: "My Details"
    },
    {
      name: 'about',
      label: 'About Me',
      icon: 'edit',
      type: 'textarea',
      value: '',
    },
    {
      name: 'age',
      label: 'My age',
      icon: 'code',
      type: 'number',
      value: '',
    },
    {
      name: 'religion',
      label: '',
      icon: 'filter_list',
      type: 'select',
      value: '',
      options: [
        'My Religions',
        'Hindu',
        'Muslim',
        'Christian',
      ]
    },
    {
      name: 'cast',
      label: 'My cast',
      icon: 'filter_hdr',
      type: 'text',
      value: '',
    },
    {
      name: 'subcast',
      label: 'My sub cast',
      icon: 'first_page',
      type: 'text',
      value: '',
    },
    {
      type: 'formBreak',
      counter: '04',
      text: "My looks"
    },
    {
      name: 'eyes',
      label: 'My Eyes color',
      icon: 'remove_red_eye',
      type: 'text',
      value: '',
    },
    {
      name: 'hair',
      label: 'My Hair color',
      icon: 'color_lens',
      type: 'text',
      value: '',
    },
    {
      name: 'weight',
      label: 'My Body weight',
      icon: 'event_seat',
      type: 'number',
      value: '',
    },
    {
      name: 'body',
      label: 'My Height',
      icon: 'expand_less',
      type: 'number',
      value: '',
    },
  ],
};
